name: kodo
description: "A chat application built with firebase."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^17.0.1
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  shared_preferences: ^2.5.4
  visibility_detector: ^0.4.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0 # Optional but recommended
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable_font_wght.ttf
        - asset: assets/fonts/inter_italic_variable_font_wght.ttf
          style: italic
